server:
  port: 10000

spring:
  profiles:
    active: dev

  application:
    name: ringly
    version: 0.0.1

  data:
    web:
      pageable:
        one-indexed-parameters: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

s3:
  bucket-name: 10daysonly
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  region-name: ${S3_REGION_NAME:kr-standard}

token:
  secret-key: ${TOKEN_SECRET_KEY}

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'

  jpa:
    hibernate:
      ddl-auto: create