name: Deploy Application

on:
  push:
    branches:
      - main

env:
  HARBOR_REGISTRY: whale.oognuyh.com
  IMAGE_NAME: 10daysonly/ringly-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - run: chmod +x gradlew

      - env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          ./gradlew jib \
            -Djib.to.auth.username=$HARBOR_USERNAME \
            -Djib.to.auth.password=$HARBOR_PASSWORD

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker login ${{ env.HARBOR_REGISTRY }} -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
            docker pull ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker stop ringly-api || true
            docker rm ringly-api || true
            docker run -d --name ringly-api -p 10000:10000 ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest