name: Deploy Application

on:
  push:
    branches:
      - main

env:
  HARBOR_REGISTRY: whale.oognuyh.com
  IMAGE_NAME: 10daysonly/ringly-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - run: chmod +x gradlew

      - env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          ./gradlew jib \
            -Djib.to.auth.username=$HARBOR_USERNAME \
            -Djib.to.auth.password=$HARBOR_PASSWORD

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: appleboy/ssh-action@v1.2.0
        env:
          HARBOR_REGISTRY: ${{ env.HARBOR_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: HARBOR_REGISTRY,IMAGE_NAME
          script: |
            docker login ${HARBOR_REGISTRY} -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
            docker pull ${HARBOR_REGISTRY}/${IMAGE_NAME}:latest
            
            docker ps -a | grep ringly-api && docker stop ringly-api || true
            docker ps -a | grep ringly-api && docker rm ringly-api || true

            docker run -d --name ringly-api -p 10000:10000 \
              -e TOKEN_SECRET_KEY=${{ secrets.TOKEN_SECRET_KEY }} \
              -e MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
              -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
              ${HARBOR_REGISTRY}/${IMAGE_NAME}:latest